name: Update News JSON

on:
  schedule:
    - cron: "0 6 */2 * *"   # every 2 days at 6 AM UTC
  workflow_dispatch:        # allows manual trigger too

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Run update script
        run: node src/services/updateNews.js

      - name: Commit & push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto-update news JSON"
          git push
