name: Update News + Embeddings + Qdrant

on:
  schedule:
    - cron: "0 6 */2 * *"   # every 2 days at 6 AM UTC
  workflow_dispatch:

jobs:
  update-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Run pipeline
        run: node src/services/pipeline.js

      - name: Commit & push updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add src/services/articles.json src/services/articles_with_embeddings.json
          git commit -m "Auto-update news, embeddings, and Qdrant sync" || echo "No changes"
          git push
